#!/bin/bash

function send_notification() {
	volume=$(amixer get Master | egrep -o '[0-9]{1,3}%')
	dunstify -a "changevolume" -u low -r "9993" -h int:value:"$volume" -i "volume-$1" "Volume: ${volume}" -t 2000
}

case $1 in
up)
	# Set the volume on (if it was muted)
	amixer set Master	2%+
  send_notification $1
	;;
down)
	amixer set Master	2%-
	send_notification $1
	;;
mute)
	amixer set Master	toggle
	if $(pamixer --get-mute); then
		dunstify -i volume-mute -a "changevolume" -t 2000 -r 9993 -u low "Muted"
	else
		send_notification up
	fi
	;;
esac
