
-- {
--   "folke/noice.nvim",
--   event = "VeryLazy",
--   dependencies = { "MunifTanjim/nui.nvim" },
--   opts = {
--     messages = { enabled = false },
--     lsp = {
--       progress = { enabled = false },
--       hover = { enabled = false },
--       signature = { enabled = false },
--     },
--     health = { checker = false },
--   },
-- },
